POST https://secure-falls-46921.herokuapp.com/api/users HTTP/1.1
content-type: application/json

{
    "name": "aryansyah",
    "email": "aryansyah@gmail.com",
    "password": "123456",
    "phone_number":"+12345999"
}
###
GET https://secure-falls-46921.herokuapp.com/api/users HTTP/1.1
content-type: application/json
###

GET https://secure-falls-46921.herokuapp.com/api/users/1 HTTP/1.1
content-type: application/json
###

DELETE https://secure-falls-46921.herokuapp.com/api/users/6 HTTP/1.1
content-type: application/json